### PR TITLE
bg color changed

### PR DESCRIPTION
**Pull request by EbYVarghese18**

### CODE REVIEW

**Comment by roshith844** [comment]
why did you choose this color??

**Comment by EbYVarghese18** [comment]
> why did you choose this color??
which color you suggesting

**Comment by roshith844** [comment]
> > why did you choose this color??
> > which color you suggesting

HEX: #34568B

**Comment by EbYVarghese18** [comment]
I have changed the color. Please review it.

**Review by roshith844 — APPROVED** [review]

**Pull request merged**
